### ISSUE TITLE
deploy-downloader fails to execute when called by cron.

### ISSUE THREAD

**Issue by brennentsmith** [pinterest/teletraan#137]
We have a functioning teletraan stack which works wonderfully except for one crucial issue - the deploy agent completely fails when called by cron. It works fine when called directly on the shell, but during execution called by cron, it fails during the `deploy-downloader` command with the following error:

```
  File "build/bdist.linux-x86_64/egg/deployd/common/executor.py", line 80, in run_cmd
    preexec_fn=os.setsid, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

We patched `common/executor.py` to print the contents of `cmd` to stdout so we could debug the issue and found that the following was occurring during the cron executed command:

```
[u'/data/nodejs/artifactname/teletraan/PRE_DOWNLOAD']
['deploy-downloader', '-f', '/etc/deployagent.conf', '-v', u'UUID-OG-A_1bb1b62', '-u', u's3://s3url/20/artifact.tar.gz', '-e', u'Environment-Name']
['deploy-downloader', '-f', '/etc/deployagent.conf', '-v', u'UUID-OG-A_1bb1b62', '-u', u's3://s3url/20/artifact.tar.gz', '-e', u'Environment-Name']
['deploy-downloader', '-f', '/etc/deployagent.conf', '-v', u'UUID-OG-A_1bb1b62', '-u', u's3://s3url/20/artifact.tar.gz', '-e', u'Environment-Name'] 
```

The respective crontab entry is:
```
* * * * * /usr/local/bin/deploy-agent -f /etc/deployagent.conf >> /var/log/deployd.log 2>&1
```

All of the respective files in the config (log directory, deployd directory, builds directory etc.) exist and are writable by the user. Everything works like a charm when the command `/usr/local/bin/deploy-agent -f /etc/deployagent.conf` is called on the shell, it's just cron which fails. 

Any ideas about this issue would be greatly appreciated!

This is on Debian 8 with python 2.7.9 and the latest version of master (as of this morning).

**Comment by sbaogang** [comment]
This has to do with the environment variables crontab inherit - try something like:
* * * * * PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/local/bin/deploy-agent -f /etc/deployagent.conf >> /var/log/deployd.log 2>&1
and see if it works

**Comment by brennentsmith** [comment]
I could have sworn that I tried setting the path last week, but that worked! Thanks @sbaogang, and sorry to bother you for something that trivial! 👍

**Comment by sbaogang** [comment]
Not at all, thanks for using Teletraan!
