### ISSUE TITLE
two pop up displays on progress bar

### ISSUE THREAD

**Issue by skapil** [pinterest/teletraan#152]
Hovering over the progress bar on current deploy page display two pop ups with same information.

![image](https://cloud.githubusercontent.com/assets/5033498/15332022/ddb8f1d8-1c18-11e6-9a4f-af2c71f67e2d.png)

Let me know, if I can help to fix the issue :)

**Comment by yujunglo** [comment]
Thanks for the question! This will be fixed by #154.
