### ISSUE TITLE
Unable to fully delete environments via API

### ISSUE THREAD

**Issue by brennentsmith** [pinterest/teletraan#158]
With the API, it is not currently possible to completely delete an environment - it is possible to delete the non-primary stages within an environment, but deleting the primary stage results in an 500 error.

Call:
```
curl -X DELETE -H "Authorization: token <token>" localhost:8080/v1/envs/environmentname/prod
```

Response:
```
{"code":500,"message":"There was an error processing your request. It has been logged (ID 9a31b752c7e8ea27)."}
```

As far as I can find, there's not a corresponding UI element to delete the environment - the only option is to disable it.

**Comment by yujunglo** [comment]
Hi Brennen,
If you want to remove the stage, you need to go to **Capacity Config** to remove Hosts and Groups. Then you will see the **Remove this Stage** button in the General Config page.
<img width="200" alt="screen shot 2016-05-25 at 12 05 53 pm" src="https://cloud.githubusercontent.com/assets/6164413/15552824/18eb305a-2271-11e6-9a3a-3e7ba6161657.png">

If this is still not working, could you please grep the log id **9a31b752c7e8ea27** in server.log under /var/log or under /tmp?
Thanks.

**Comment by brennentsmith** [comment]
Hi Yu-Jung,

Thanks for the quick reply - soon as I removed all of the groups from the stage, the remove stage button appeared (and worked without issue). Thanks for A) including that safety check and B) letting me know. 

I don't think that this is mentioned anywhere in the documentation, but if I totally overlooked it, my apologies!

**Comment by sbaogang** [comment]
Right, env delete is not in the doc, will add it. Thanks for your input!
