### ISSUE TITLE
username and password for teletraan UI 

### ISSUE THREAD

**Issue by sergeyr87** [pinterest/teletraan#161]
hi 
how can i create a username access to the webui?

**Comment by sbaogang** [comment]
Teletraan does not manage user identities, but rather it integrates with OAuth provider, such as google openid, to authenticate user. To enable authentication/authorization, you need to configure them in both the deploy-board and deploy-service. see both manage.py and this page https://github.com/pinterest/teletraan/wiki/Setting-up-user-roles for more details, let us know if you have any further questions

**Comment by brennentsmith** [comment]
We were able to get Google OAuth working with Teletraan, but it did require some minor modifications to deploy-board and deploy-service due to how keys were extracted. If I have time, I'll put together a PR and tutorial.

**Comment by sergeyr87** [comment]
great thanks :)

**Comment by sbaogang** [comment]
Close this for now, let know if there is any question setting up OAuth integration. thanks!
