### ISSUE TITLE
When Script Tokens are enabled, POST's to /v1/system/ping with correct Authorization header return 403

### ISSUE THREAD

**Issue by brennentsmith** [pinterest/teletraan#168]
We recently enabled OAUTH for deploy-board and the deploy service so we can use role based permissions (dev deploy to staging, eng deploy to prod). Everything is working properly on the UI end except that we now cannot get any deploy-agents to communicate with deploy-service. 

We discovered that due to this change (uncommenting the authorization and authentication blocks in `server.yaml`), deploy-service is now requiring the "Authorization: token <token>" header. As a result, we generated new script tokens for the specific environment, and added it to the respective deploy-agent config. 

We expected that this would work - however we are now receiving 403 errors on the deploy-agent ping. It appears that the token is somewhat accepted by the deploy-service, as it's not calling to the Oauth Token provider (when we place a fake/broken token in the request, it responds with a 401 from the Oauth provider). 

Is there a way to A) have the deploy-agents stay on anonymous auth, B) determine why the script tokens are not being accepted (specific debug point)

Curl with correct token:
```
curl -v -k -H "Authorization: token <token>" -H "Content-Type: application/json" -X POST -d '{"hostName": "aw-mapi-consumer3", "hostId": "371008528", "reports": [{"failCount": 0, "envId": "xI9Nd0RgTnWel4VlSU52Ig", "errorMessage": null, "deployStage": "SERVING_BUILD", "errorCode": 0, "deployId": "BWLYzB70QOeVdtIjKRIQ-w", "deployAlias": null, "agentStatus": "SUCCEEDED"}], "groups": ["speedtest-mobile-reports-prod-consumer"], "hostIp": "127.0.0.1"}' http://deploy.internal.ookla.com:8080/v1/system/ping
* Hostname was NOT found in DNS cache
*   Trying 172.16.1.84...
* Connected to deploy.internal.ookla.com (172.16.1.84) port 8080 (#0)
> POST /v1/system/ping HTTP/1.1
> User-Agent: curl/7.38.0
> Host: deploy.internal.ookla.com:8080
> Accept: */*
> Authorization: token <token>
> Content-Type: application/json
> Content-Length: 356
>
* upload completely sent off: 356 out of 356 bytes
< HTTP/1.1 403 Forbidden
< Date: Thu, 02 Jun 2016 17:26:08 GMT
< Content-Type: application/json
< Content-Length: 40
<
* Connection #0 to host deploy.internal.ookla.com left intact
```

Curl with Incorrect token: 
```
curl -v -k -H "Authorization: token <faketoken>" -H "Content-Type: application/json" -X POST -d '{"hostName": "aw-mapi-consumer3", "hostId": "371008528", "reports": [{"failCount": 0, "envId": "xI9Nd0RgTnWel4VlSU52Ig", "errorMessage": null, "deployStage": "SERVING_BUILD", "errorCode": 0, "deployId": "BWLYzB70QOeVdtIjKRIQ-w", "deployAlias": null, "agentStatus": "SUCCEEDED"}], "groups": ["speedtest-mobile-reports-prod-consumer"], "hostIp": "127.0.0.1"}' http://deploy.internal.ookla.com:8080/v1/system/ping
* Hostname was NOT found in DNS cache
*   Trying 172.16.1.84...
* Connected to deploy.internal.ookla.com (172.16.1.84) port 8080 (#0)
> POST /v1/system/ping HTTP/1.1
> User-Agent: curl/7.38.0
> Host: deploy.internal.ookla.com:8080
> Accept: */*
> Authorization: token <faketoken>
> Content-Type: application/json
> Content-Length: 356
>
* upload completely sent off: 356 out of 356 bytes
< HTTP/1.1 401 Unauthorized
< Date: Thu, 02 Jun 2016 17:29:28 GMT
< Content-Type: application/json
< Content-Length: 202
<
* Connection #0 to host deploy.internal.ookla.com left intact
{"code":401,"message":"Failed to authenticate user. java.io.IOException: Server returned HTTP response code: 401 for URL: https://www.googleapis.com/userinfo/v2/me?access_token=<faketoken>"}
```

The only respective log entry is in `deploy-service/access.log` and it states:
First curl: 
```
172.16.1.192 - - [02/Jun/2016:17:30:42 +0000] "POST /v1/system/ping HTTP/1.1" 403 40 "-" "curl/7.38.0" 2
```
Second curl: 
```
172.16.1.192 - - [02/Jun/2016:17:30:33 +0000] "POST /v1/system/ping HTTP/1.1" 401 202 "-" "curl/7.38.0" 5060
```

**Comment by sbaogang** [comment]
Hi Brennent, thanks for the question. We did not make this part clear in the wiki, there are basically two ways to handle this:

1. If you run the teletraan agent service independently, as described here: https://github.com/pinterest/teletraan/wiki/Introduction, then you could configure the agent-service independently to disable authentication/authorization.

2. If you do run both agent-service and deploy-service in the same process, then you need to manually, meaning use SQL command, to issue yourself a script token just for ping. The syntax will be something like:

insert into tokens_and_roles values ("pinger","*","SYSTEM",RANDOM-22-CHAR-STRING,'PINGER',1444364361894)

You could change the timestamp to any milliseconds in the future. You then would have to configure the deploy-agent to use the token: https://github.com/pinterest/teletraan/blob/master/deploy-agent/deployd/conf/agent.conf

Unfortunately, we do not have an UI support for this ( we do not have UI for global resource protection, only per env for now ). We will consider to add it later.

Let us know if you have any questions when setting the above up.

**Comment by brennentsmith** [comment]
Hi Sbaogang, thank you for the descriptive (and very helpful) response. From a pragmatic perspective, how would one go about separating the teletraan agent from the deploy-service? 

1) Would you run a second instance of deploy-service, with the same mysql endpoints, but with different auth settings and ports (to prevent collisions with the first instance)?
2) Is there a flag passed at initialization to make it run in agent mode?
3) Other? 

Lastly, do you have a recommended "best practice" of the two options you provided? The second option appears most straightforward (and retains a semblance of auth on ping), but I'm worried that doing manual database modifications will cause issue in the future.

**Comment by sbaogang** [comment]
At Pinterest, we run agent-service and deploy-service in their owner cluster for the following reasons:
1. Given 10+K hosts pinging every minute, agent-service is much busier and we do not want to add extra load from the deploy-service side.
2. Agent-service code path is pretty separate from the deploy-service code path, most of our code changes are in the deploy-service side, so we do not have to update agent-service every time. 

To run in agent mode, I think the only difference is to run com.pinterest.teletraan.TeletraanAgentService, instead of com.pinterest.teletraan.TeletraanService. 

I would not worry about the manual SQL operation though, to issue a global token is very rare, it should just happen a couple of times in Teletraan lifetime ( that is why we do not have an UI yet, service owners who deploy code do not need them). We would keep the future DB change backward compatible, and we will also provide UI for the global token as well.

**Comment by brennentsmith** [comment]
Excellent, thank you very much for the clarification and assistance. We ended up just doing the SQL statement - we don't have as many hosts as you do (high hundreds), and we already had clustering setup for the combined deploy-service/teletraan-agent-service. 

It worked like a charm! We've been very impressed with Teletraan, thank you again for open sourcing it.

**Comment by sbaogang** [comment]
you are certainly welcome!
