### ISSUE TITLE
No logout option within GUI

### ISSUE THREAD

**Issue by brennentsmith** [pinterest/teletraan#170]
Currently there is no way to log out of a session within the GUI. This does cause some issues with other OAUTH providers which allow users to select multiple accounts during the login process. 

In the event that a user selects a non-desired account during the login process, they are stuck in an orphaned state as they are unable to log out to change accounts.

**Comment by nickdechant** [comment]
Hey Brennen,
Thanks for bringing this up, I'll go ahead and put in a logout button. I'll post here when it's available.

**Comment by Arch88** [comment]
@nickdechant  is this added ?

**Comment by sbaogang** [comment]
the logout option is added, let us know if there is any issues/questions with this fix. Thanks for the request.
