### ISSUE TITLE
Hosts are duplicated in GUI - one appears to be non-functional and causes deploy to fail

### ISSUE THREAD

**Issue by brennentsmith** [pinterest/teletraan#184]
When running a standard deploy, servers sometimes are duplicated in the GUI. This causes the deploy to fail, as one of the hosts in the gui fails to deploy. The host ID's are the same for both hosts, and it was not changed during the deploy. Under the host's details, it shows two deploys rather than just one. I have also waited much longer than the `SimpleAgentJanitor` thresholds.

I'm not sure in this case what logs would be helpful, but here are screenshots of the behavior:

Deploy interface: http://ookla.d.pr/1HC4
Host Information: http://ookla.d.pr/TsSA

Is it possible to remove the erroneous host, and do you have any ideas what may have caused this/how to prevent it? 

It's happened 3 times on different deploys, and the only way we have solved it is destroying the stage, which isn't a great solution at scale.

**Comment by brennentsmith** [comment]
We were able to remove the "root" host from the GUI (shutting it down), but the duplicate still is visible within the stage and is causing issues with deploys. Oddly, the details within the host info page are now gone: http://ookla.d.pr/waNF

**Comment by sbaogang** [comment]
I will take a look - it will help if you provide bit more info - mostly on the deploy agent side, do we have two hosts with the same name but we changed host id in between? do you have multiple envs setup for the same host/group?

**Comment by sbaogang** [comment]
also, can you post your current deploy screenshot like the one you post before: http://ookla.d.pr/1HC4

**Comment by brennentsmith** [comment]
Hi sbaogang - thanks for taking a look! 

For deploy agents, we were performing the following within Chef to generate the host info file:

`machineID = Zlib::crc32(node['hostname'].to_s + node['fqdn'].to_s + node['ip'].to_s + node['mac_address'].to_s)`
```
<% if node['teletraan_agent']['host_info']['groups'].length > 0%>
groups=<%=node['teletraan_agent']['host_info']['groups'].join(",")%>
<% end %>
<% if node['teletraan_agent']['host_info']['id'] != ""%>
id=<%=node[:teletraan_agent][:host_info][:machineID] %>
<% end %>
<% if node['teletraan_agent']['host_info']['host'] != ""%>
hostname=<%=node[:teletraan_agent][:host_info][:host] %>
<% end %>
<% if node['ipaddress'] != "127.0.0.1"%>
ip=<%=node['ipaddress'] %>
<% end %>
```
Each group is tied to a specific env -> stage, there are no overlaps. 

After I posted the message last night - I re looked at the logic above, and realized that there was a possibility for an ID and hostname to be decoupled if the other values in the crc32 were changed. This would cause the URL to stay the same (since the hostname still was the same) but a second ID was attached to the same host. 

I'm not completely familiar with the inner workings of how ID's are used (and it was 1am, so I wasn't capable of a deep code review), but I could see that being an issue.

I then modified the host_info generation to the following: 

`machineID = Zlib::crc32(node['hostname'].to_s)`
```
<% if node['teletraan_agent']['host_info']['groups'].length > 0%>
groups=<%=node['teletraan_agent']['host_info']['groups'].join(",")%>
<% end %>
<% if node['teletraan_agent']['host_info']['id'] != ""%>
id=<%=node[:teletraan_agent][:host_info][:machineID] %>
<% end %>
<% if node['teletraan_agent']['host_info']['host'] != "" && node['teletraan_agent']['host_info']['id'] != "" %>
hostname=<%=node[:teletraan_agent][:host_info][:host] %>_<%=node[:teletraan_agent][:host_info][:id] %>
<% end %>
<% if node['ipaddress'] != "127.0.0.1"%>
ip=<%=node['ipaddress'] %>
<% end %> 
```

This was to ensure that the hostname is always directly tied to the ID, and the ID cannot change without the hostname changing. I also attached the ID on the hostname so it would instantiate new hosts and for debugging.

We cleared out the stages after the changes above to resolve the issue, but I left one "broken" stage for debugging. A screenshot is here: http://ookla.d.pr/1dcGC and (odd duplicate) http://ookla.d.pr/1739q and (server with new host_info logic) http://ookla.d.pr/11Pyu

I hope this makes sense - and please let me know if I'm completely off on the ID generation.

**Comment by sbaogang** [comment]
Hmm, looking at the code, I believe we should delete the staled agent record in the DB. In your teletraan service service.log, can you find error, such as:

AgentJanitor Failed to delete all records for host

that indicates we tried to delete the staled agent, but failed, which is the only thing I can think of right now...

**Comment by brennentsmith** [comment]
We determined that the issue was indeed due to the issue of Chef creating multiple ID's when using the CRC32 of the network interface as it returns the interfaces in a non-deterministic order. For Chef, we recommend taking a CRC32 or similar normalizing function of the hostname for the ID.
