### ISSUE TITLE
default vagrant file maybe should export 8080?

### ISSUE THREAD

**Issue by WarrenWilkinson** [pinterest/teletraan#252]
I've been toying with this, a few hurdles I ran into:

 * Vagrantfile doesn't export 8080 (deploy-service) by default, so you need to add that before you can publish a build.
 * Docs don't mention that "v1/build" is a target on the deploy-service and not the deploy-board.
 * That commit-date is an integer, and not a string (and can be generated with git show -s --format="%ct000")

Other than that, looking cool so far.

**Comment by sbaogang** [comment]
Thanks for the suggestion, will expose 8080. I think we assumed the publish command will run inside vagrant VM.
Updated the doc, thanks again for the suggestion.

**Comment by sbaogang** [comment]
fixed by https://github.com/pinterest/teletraan/pull/255, closing
