### ISSUE TITLE
Error while running teletraan server

### ISSUE THREAD

**Issue by Arch88** [pinterest/teletraan#267]
Error: Could not find or load main class com.pinterest.teletraan.TeletraanService

**Comment by sbaogang** [comment]
Do you have more context how to reproduce this?

**Comment by Arch88** [comment]
Compile the Teletraan server code:
  $ cd $TELETRAAN_ROOT/deploy-service
  $ mvn clean package -DskipTests

**Comment by Arch88** [comment]
./teletraanservice/bin/run.sh start
Starting Teletraan server...
Teletraan server started.
:~/teletraan/deploy-service$ Error: Could not find or load main class com.pinterest.teletraan.TeletraanService

**Comment by Arch88** [comment]
The server starts and then encounters this error

**Comment by sbaogang** [comment]
I could not reproduce with latest version. Are you sure the mvn build command finished successfully?

**Comment by Arch88** [comment]
[INFO] teletraan .......................................... SUCCESS [  0.355 s]
[INFO] common ............................................. FAILURE [  2.799 s]
[INFO] teletraan-service .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.327 s
[INFO] Finished at: 2016-11-01T13:09:13-04:00
[INFO] Final Memory: 10M/25M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project common: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :common

**Comment by sbaogang** [comment]
You would need to install and use java8.

**Comment by Arch88** [comment]
I have installed java 8:
$ java -version
openjdk version "1.8.0_91"

**Comment by sbaogang** [comment]
can you copy and paste the result of the following command:
mvn -version

**Comment by Arch88** [comment]
Apache Maven 3.3.9

**Comment by sbaogang** [comment]
can you also run "echo $JAVA_HOME", and "$JAVA_HOME/bin/java -version"?

**Comment by Arch88** [comment]
/usr/bin/java

**Comment by Arch88** [comment]
version -- 1.8.0_91

**Comment by Arch88** [comment]
You can close this issue, the problem was with setup of environment variables.
