### ISSUE TITLE
Publish using Swagger

### ISSUE THREAD

**Issue by Arch88** [pinterest/teletraan#277]
I am trying to build using swagger POST method, I am attaching the screenshot, the build is published, but I couldnt get it on the UI board of teletraan. I tried the POST method from REST API to teletraan as well.
![screenshot 463](https://cloud.githubusercontent.com/assets/18602957/20611140/a0180bfc-b272-11e6-90c1-bdcf43d5a339.png)

**Comment by Arch88** [comment]
@Jakobo

**Comment by sbaogang** [comment]
Do you have the env configuration page setup correctly? e.g.

![image](https://cloud.githubusercontent.com/assets/6217693/20680104/7e8ba16e-b552-11e6-8b0e-29e84b7f3b8a.png)

**Comment by Arch88** [comment]
Yes, I have it configured correctly, builds get published from console correctly.

![screenshot 479](https://cloud.githubusercontent.com/assets/18602957/20681988/061f83ae-b574-11e6-90b9-4ad268b6e7be.png)

**Comment by sbaogang** [comment]
Could you check DB to make sure the build is indeed in builds table? You can also take a look at https://github.com/pinterest/teletraan/blob/master/deploy-sentinel/quickstart.py, it contains a python based script to publish build

**Comment by Arch88** [comment]
The builds gets published successfully from console with the quickstart.py script, but if I try to publish using Swagger UI, it doesnt publish the build I tried even with RESTClient.

**Comment by sbaogang** [comment]
Looks like you would have too specify repo, branch, commit as well. The following worked for me:

{ 
   "name":"deploy-sentinel",
   "artifactUrl":"http://localhost/build-artifact.tar.gz",
   "repo":"foo",
   "branch":"master",
   "commit":"12345"
}

Sorry for the confusion, I updated the doc as well. Thanks!
