### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by Arch88** [pinterest/teletraan#281]
Can you explain a bit on how to do authentication and authorization using OAuth for teletraan. I encountered following error while uncommenting on server.yaml file 

Starting Teletraan server...
/home/archana/Desktop/workspace/teletraan/deploy-service/teletraanservice/bin/server.yaml has an error:
  * Failed to parse configuration at: db; Could not resolve type id 'role' into a subtype of [simple type, class com.pinterest.teletraan.config.DataSourceFactory]: known type ids = [DataSourceFactory, embedded, mysql, zkmysql]
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.pinterest.teletraan.TeletraanServiceConfiguration["db"])

**Comment by sbaogang** [comment]
Can you take a look https://github.com/pinterest/teletraan/wiki/Setting-up-user-roles and let us know if it helps?

**Comment by Arch88** [comment]
**This is from databases;** 

mysql> select * from users_and_roles;
+-----------+-----------------+---------------+----------+
| user_name | resource_id     | resource_type | role     |
+-----------+-----------------+---------------+----------+
| admin     | 1111                 | admin         | admin    |
| tester1    | 12334                | test             | tester   |
| archana   | 1235                  | user            | user     |
| archana   | deploy-sentinel | ENV           | ADMIN    |
| tester1    | deploy-sentinel | ENV            | OPERATOR |
| tester2    | deploy-sentinel | ENV            | OPERATOR |

+--------- --+-----------------+---------------+----------+
6 rows in set (0.00 sec)

**server.yaml file is edited as below:**

authentication:
  # Authentication type: allowed values are token, anonymous. The Token based authentication
  # Note: anonymous authentication is the same as disable authentication all together
  type: token

  # OAuth provider url
  #userDataUrl: https://auth.pinadmin.com/api/me/
  userDataUrl: https://accounts.google.com/o/oauth2/auth

  #OAuth provider - either pinadmin (internal) or openid
  oauthProvider: pinadmin

  # Optional. token cache
  tokenCacheSpec: maximumSize=1000,expireAfterWrite=10m


  #Token based Authorization: by default is disabled.

  authorization:
  # Authorization type: allowed values are role, open. See documentations for more details.
  # Note: open authorization is the same as disable authorization all together
  type: ADMIN
  # Optional. token cache
  roleCacheSpec: maximumSize=10000, expireAfterAccess=10m


**error on console: -**

Starting Teletraan server...
/home/archana/Desktop/workspace/teletraan/deploy-service/teletraanservice/bin/server.yaml has an error:
  * Failed to parse configuration at: db; Could not resolve type id 'ADMIN' into a subtype of [simple type, class com.pinterest.teletraan.config.DataSourceFactory]: known type ids = [DataSourceFactory, embedded, mysql, zkmysql]
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.pinterest.teletraan.TeletraanServiceConfiguration["db"])

**Comment by sbaogang** [comment]
You can wait for https://github.com/pinterest/teletraan/pull/285, which also provided a complete example of google openid integration. For your current setting, 

type: ADMIN

#authorization:
  # Authorization type: allowed values are role, open. See documentations for more details.
  # Note: open authorization is the same as disable authorization all together
  #type: role

there is no "ADMIN" type.


oauthProvider: pinadmin

this is no oauthProvider either

**Comment by Arch88** [comment]
Ok Thank You, Much appreciated.

**Comment by sbaogang** [comment]
close for now since https://github.com/pinterest/teletraan/pull/285 has been merged. Let know if there are other issues. thanks!
