### ISSUE TITLE
Error In the Web UI

### ISSUE THREAD

**Issue by vishnuraj-applift** [pinterest/teletraan#327]
'NoneType' object is not iterable

After I installed the teletraan under my user and tried to create a new Env as per the documentaion, I am getting the following error.

![image](https://cloud.githubusercontent.com/assets/20416010/21767809/1df7e07c-d69c-11e6-97f9-57c68932218e.png)

**Comment by sbaogang** [comment]
can you elaborate how you install teletraan? I followed the instruction here, https://github.com/pinterest/teletraan/wiki/Setup-Teletraan-development-environment, not able to reproduce.
