### ISSUE TITLE
Can not create environment

### ISSUE THREAD

**Issue by alex-bender** [pinterest/teletraan#339]
I've installed Python 2.7, virtualenv, mysql, Java 8 into dockerized Ubuntu, configured server.yml to look at local mysql database, started `service` and `deploy board`, but after 'create env' submit I got error:

```
Teletraan failed to call backend server. 
Contact your friendly Teletraan owners for assistance. 
Hint: 500, {"code":500,"message":"There was an error processing your request. It has been logged
```

vagrant version works fine, but what's the problem with `Manual Option`?

here is a traceback from `/tmp/deploy_board/service.log`

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/deploy-board/deploy_board/webapp/env_views.py", line 566, in post_create_env
    environs_helper.create_env(request, data)
  File "/home/deploy-board/deploy_board/webapp/helpers/environs_helper.py", line 92, in create_env
    return deployclient.post("/envs", request.teletraan_user_id.token, data=data)
  File "/home/deploy-board/deploy_board/webapp/helpers/deployclient.py", line 78, in post
    return self.__call('post')(path, token, params=params, data=data)
  File "/home/deploy-board/deploy_board/webapp/helpers/decorators.py", line 67, in f_retry
    return f(*args, **kwargs)
  File "/home/deploy-board/deploy_board/webapp/helpers/deployclient.py", line 65, in api
    "Hint: %s, %s" % (response.status_code, response.content))
TeletraanException: Teletraan failed to call backend server. Contact your friendly Teletraan owners for assistance. Hint: 500, {"code":500,"message":"There was an error processing your request. It has been logged (ID ee4fbdc96583d8f8)."}
```

**Comment by lilida** [comment]
Hi Alex,

Have you provisioned the database? 

See: https://github.com/pinterest/teletraan/wiki/Setup-Teletraan-using-Docker-and-Docker-compose

**Comment by alex-bender** [comment]
Hi!
Thanks for reply.
Yes, I've tried both variants, with embedded DB and not.
In firs case I've created database and then `source deploy.sql` right from mysql console. (Also has tried via deploydb.sh)

**Comment by alex-bender** [comment]
Btw, I don't know if it is related, but docker-compose also don't work.
http://localhost:8888/ gives error: 
`HTTPConnectionPool(host='localhost', port=8080)`

**Comment by lilida** [comment]
8080 is the deploy service that dashboard calling to? Do you have it actually started (deploy-service container) successfully?

**Comment by alex-bender** [comment]
Hm, strange. Now deploy-service_1 isnt started, because:
`deploy-service_1  | Error: Could not find or load main class com.pinterest.teletraan.TeletraanService`
I've cloned repository again and error is the same..

**Comment by alex-bender** [comment]
Sorry, I'm from python land, missed part where I need to compile teletraan.
