### ISSUE TITLE
Review apps

### ISSUE THREAD

**Issue by chrislloyd** [pinterest/teletraan#350]
Heroku has the functionality to be able to deploy [review apps](https://devcenter.heroku.com/articles/github-integration-review-apps) for projects on a per PR basis. It's incredibly useful when trying to review code as you inspect visual changes via. a deployment and run integration tests on it.

Is this possible with Teletraan?

**Comment by lilida** [comment]
@chrislloyd
 Today,  You can upload a private build (tar file) and deploy it manually.  My understanding is that auto creation and deployment is useful for the app with UI to people to review the PR, is that correct? But it is too heavy to deploy a single pr on a single host now. After we have better container support, this can be much light weighted and we can look into here.

**Comment by chrislloyd** [comment]
Yes, container support does make this really easy. Is there a timeline or roadmap for container support in teletraan?

**Comment by lilida** [comment]
We can take offline talking about the internal container support schedule.
@haom-pinterest
