### ISSUE TITLE
feature request: connect to MySQL over SSL with client certificate

### ISSUE THREAD

**Issue by yosida95** [pinterest/teletraan#359]
I'm setting up and evaluating Teletraan for our primary deployment manager. In our infrastructure requirements, we have to connect to MySQL over SSL with a client certificate and a self-signed server certificate. I looked for ways to do this for a while, but there seems to be no ways.

So it would be great if there ware a way to connect to MySQL over SSL.

(I joined teletraan-users@googlegroups.com but it doesn't seem to be active; If GitHub Issues is not appropriate place to do feature request, please close this and point me an appropriate place. )

**Comment by lilida** [comment]
I don't think it comes  out of box. Per my understanding, it just needs some options to be enabled in connection string. But it shouldn't be too hard to add it. Probably just change MysqlDataSourceFactory.java . Do you have a sample connection string you want to use?

**Comment by yosida95** [comment]
Nope.  I'm not familiar with JDBC and also Java.  As I read [Connector/J documentation](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html), the parameter would looks like `&useSSL=true&requireSSL=true&verifyServerCertificate=true&clientCertificateKeyStoreUrl=/path/to/client-cert.jks&clientCertificateKeyStoreType=JKS&trustCertificateKeyStoreUrl=/path/to/server-cert.jks&trustCertificateKeySToreType=JKS`

An alternative MySQL client command line to intended to make same connection is `mysql -u user -p --ssl-cert /path/to/client-cert.pem --ssl-key=/path/to/client-key.pem --ssl-ca /path/to/server-ca.pem`

The transformation to JSK from PEM is done by converting PEM to DER using openssl, then import it to JKS keystore using keytool.

**Comment by lilida** [comment]
I have made a change so you can pass connection properties, for ex,

db:
  # DB backend type. Allowed values are: embedded, mysql.
  type: mysql

  # Mysql instance configurations
  host: ${TELETRAAN_DB_HOST:-localhost}
  port: 3306
  userName: root
  password:
  connectionProperties:
            useSSL: true
            verifyServerCertificate: true
...

https://github.com/pinterest/teletraan/pull/364

**Comment by lilida** [comment]
Merged

**Comment by yosida95** [comment]
Thank you for your quick support!  I'll try the latest revision in next few days.
