### ISSUE TITLE
AutoDeploy doesn't respect cron schedule as expected

### ISSUE THREAD

**Issue by jaredlwong** [pinterest/teletraan#377]
When I set a schedule for autodeploy, the expected behavior is that the deploy only happens within some reasonable amount of time at or after when the schedule is set.

For example, `0 0 11 * * *` should only fire at 11am utc or within some reasonable amount of time after it, say up to 30 minutes after 11am. This buffer time should be set the same everywhere, or configurable.

As it is, the current algorithm does the following in https://github.com/pinterest/teletraan/blob/a4201f2a2f2e17b14ed8a552ceab2f0d2a788f4a/deploy-service/teletraanservice/src/main/java/com/pinterest/teletraan/worker/AutoPromoter.java#L275

In the autodeploydue function:
* get last deploy time
* calculate the next time (after the last deploy time) when the cron is satisfied
* if the current time is after the next calculated time, it deploys

This has several unintended side effects:
* On the first deploy, it deploys immediately
* If deploys are made available at a smaller frequency than the cron schedule's frequency, the deploys will be auto deployed as soon as they are ready, rather than within the expected time window

This is functionality important for systems which should only deploy at certain times of day. For example, we have a critical tool which uses lots of memory during the day to hold User's data and perform fast computation. Many long-running computations are performed during the day. Deploys may not happen every day, but when they do, we want them published at 3-4am when Users are generally not working.

**Comment by lilida** [comment]
@jaredlwong Thanks for writing the description. I agree with your first deploy point. For the 2nd, I haven't fully got it, do you mean manually deploys very frequently can result auto deploy triggered?

**Comment by jaredlwong** [comment]
Here's an example:

Say I set the schedule to `0 0 11 * * *`, which should deploy every day at 11AM UTC.

Then I have this timeline:
* Build available on Monday at 00:00 UTC
* Auto Deploy on Monday at 11:00 UTC
* Build available on Wednesday at 15:00 UTC
* Auto Deploy on Wednesday at 15:00 UTC

The second auto deploy isn't expected to happen. But it happens because of the autoDeployDue calculation laid out above. The next deploy time after "Monday at 11:00 UTC" is "Tuesday at 11:00 UTC". "Wednesday at 15:00 UTC" > "Tuesday at 11:00 UTC", so auto deploy occurs.

**Comment by lilida** [comment]
@jaredlwong  Thanks for the detail. Yes I agree with you on the schedule perspective. Will plan a fix on it. + @sbaogang to ensure we don't misunderstand any original design

**Comment by haom-pinterest** [comment]
Baohang is on vacation. @jihe might also know the context.

-ming

**Comment by jinruh** [comment]
yes. I think what @jaredlwong said is true.

**Comment by haom-pinterest** [comment]
Sop I will assume there is no specific reason for the way it works today.
We can tighten up the timing.

**Comment by jinruh** [comment]
We can change the behavior to be:
If the build is not available at schedule time, skip the deploy. and do it in next scheduled time.

**Comment by haom-pinterest** [comment]
That sounds more intuitive to users.

**Comment by lilida** [comment]
Agree that is more intuitive.  Will send a PR later

**Comment by haom-pinterest** [comment]
Thanks, Lida!

**Comment by jinruh** [comment]
Thanks @lilida for doing this!

**Comment by lilida** [comment]
https://github.com/pinterest/teletraan/pull/382 
https://github.com/pinterest/teletraan/pull/383
https://github.com/pinterest/teletraan/pull/384

**Comment by lilida** [comment]
Fixed and rolled out
