### ISSUE TITLE
Improve teletraan GC behavior

### ISSUE THREAD

**Issue by hrjaco** [pinterest/teletraan#506]
Currently when it's doing GC, it's doing it globally. it searches the build download dir, and keeps num_builds_to_retain builds. However, if there are >= 2 build target sharing the same build dir, the GC would potentially remove all the builds from one build target.

Instead, it should do it separately for each build target. For each build target, search for the builds with the given build name, and try to keep those builds under num_builds_to_retain.

**Comment by lilida** [comment]
https://github.com/pinterest/teletraan/pull/509
