### ISSUE TITLE
How to separate developers permissions in teletraan?

### ISSUE THREAD

**Issue by a93ushakov** [pinterest/teletraan#53]
Or git audit should be used for permissions restriction ?

**Comment by michaelfu** [comment]
@a93ushakov I am not sure I understand your question. 

Do you mean permission control for Teletraan users to deploy to specific environments? Then it is described in https://github.com/pinterest/teletraan/wiki/Setting-up-user-roles.

Or if you mean permission control for developers to commit changes to Teletraan repo, then we have a core team with the write permission to the master repo.

**Comment by a93ushakov** [comment]
I searched `Setting-up-user-roles` ;

thank you for reply.
