### ISSUE TITLE
`pip install deploy-agent` doesnt work

### ISSUE THREAD

**Issue by damouse** [pinterest/teletraan#542]
Based on [the wiki documents](https://github.com/pinterest/teletraan/wiki/Integrate-with-Teletraan#run-deploy-agents) I understood that `deploy-agent` would be available through pypi, but running `pip install deploy-agent` doesn't work. Is the intended usage to install manually via local install?

**Comment by lilida** [comment]
I think we don't put it on pypi although it was installed via pip from our internal repo. The external usage is either installing manually or uploading to private internal repo
