### ISSUE TITLE
Release Cadence? Last release was 2 years ago.

### ISSUE THREAD

**Issue by kingsquirrel152** [pinterest/teletraan#557]
I was curious if there are plans on creating new releases? As it stands, https://github.com/pinterest/teletraan/releases/tag/v1.0.1 is 2 years old. Is it expected that master branch is stable?

**Comment by lilida** [comment]
We are in the status where our production directly pulls the head of master. So I'd consider master is stable. But sure I can create a release tag.

**Comment by kingsquirrel152** [comment]
Cool! Knowing _master is gold_ -> thats good enough for me. Thanks!
