### ISSUE TITLE
Pinging pinterest jira in env_landing

### ISSUE THREAD

**Issue by kingsquirrel152** [pinterest/teletraan#558]
Not an error really, just spammy. 
Link:
https://github.com/pinterest/teletraan/blob/44877793307f45ee543a09909ed8862d2c675052/deploy-board/deploy_board/templates/deploys/warning_no_deploy.tmpl#L11

Does not seem to be behind a `IS_PINTEREST` guard.

**Comment by sulixu** [comment]
fixed with https://github.com/pinterest/teletraan/pull/559

**Comment by kingsquirrel152** [comment]
👍
