### ISSUE TITLE
Undocumented things

### ISSUE THREAD

**Issue by kingsquirrel152** [pinterest/teletraan#560]
So apologies if I missed something. The quick start guide (and vagrant image + demo script) seem to pull from the last release which is over two years old. It appears to me that the documentation + usability outside of pinterest is a little bit broken. 

Specifically around these environment variables that dont seem to have any documentation:
https://github.com/pinterest/teletraan/blob/6fa1e25a28b16e09c6f4300bd6bf482c51cc88ee/deploy-board/deploy_board/settings.py#L68

```
grep -r CMDB_API_HOST *
deploy-board/deploy_board/webapp/host_views.py:from deploy_board.settings import IS_PINTEREST, CMDB_API_HOST, CMDB_INSTANCE_URL, CMDB_UI_HOST, PHOBOS_URL
deploy-board/deploy_board/webapp/host_views.py:    host_url = CMDB_API_HOST + CMDB_INSTANCE_URL + host_id
deploy-board/deploy_board/settings.py:CMDB_API_HOST = os.getenv("CMDB_API_HOST")
```

I've got master running in out lab, but those env vars are not set to anything which causes the deploy board to not be happy when navigating around:
Error snip:
```
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7faee081e1e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7faeddfc5050>,
 'wsgi.input': <socket._fileobject object at 0x7faedf2692d0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/deploy-board/deploy_board/webapp/host_views.py", line 167, in get
    host_details = get_host_details(host_id)
  File "/opt/deploy-board/deploy_board/webapp/host_views.py", line 86, in get_host_details
    host_url = CMDB_API_HOST + CMDB_INSTANCE_URL + host_id
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

I'd be happy to make a PR to add some defaults, but I have no idea what the defaults should be. Any chance someone who knows could drop a note here with some insight? (Or even better - update with some defaults?)

Thank you very much!

**Comment by lilida** [comment]
Thanks for letting us know. The vagrant has not been updated for a while and docker containers are what we are using today. The error you listed is a bug. These codes are Pinterest specific and depending on Pinterest config and infra. It should be fixed by adding IS_PINTEREST check and return empty string

**Comment by kingsquirrel152** [comment]
So what I ended up doing was just fixing the python exception, and assume error handling downstream would resolve if this format was incorrect (easy fix in one spot, until IS_PINTEREST can be sprinkled where needed):

```python
# Serviceframework add-on vars
SERVICE_RATELIMIT_CONFIG_URL = os.getenv("SERVICE_RATELIMIT_CONFIG_URL")
STATSBOARD_API_FORMAT = os.getenv("STATSBOARD_API_FORMAT", "OFF")
RATELIMIT_ENABLED_METRIC_FORMAT = os.getenv("RATELIMIT_ENABLED_METRIC_FORMAT", "OFF")
ENABLING_SERVICE_RATELIMIT_URL = os.getenv("ENABLING_SERVICE_RATELIMIT_URL", "OFF")
KAFKA_MSGS_DELIVERED_METRIC = os.getenv("KAFKA_MSGS_DELIVERED_METRIC", "OFF")
DASHBOARD_URL_ENDPOINT_FORMAT = os.getenv("DASHBOARD_URL_ENDPOINT_FORMAT","OFF")
```

After patching above, I ran into an issue where capacity changes for an environment would not save. Digging into it led me here:
https://github.com/pinterest/teletraan/blob/master/deploy-board/deploy_board/templates/configs/capacity.tmpl#L67

Basic issue appears to be if my environment is not a cluster (it isnt) then we blowup at the second index on `basic_cluster` which is nil. The ternary below cleared the exception, and restored functionality. 

```javascript
var image = info.basic_cluster ? info.basic_cluster_info.base_image_info : null;
```

Outside of the above issues, we've been able to spin up a deploy-service and deploy-board in our staging environment for testing. Very nice project!

Im happy to make a clean PR with the above in it if the project would like the input. (And if the code is on the right track, my changes feel a bit hacky)

**Comment by lilida** [comment]
Thanks for checking this. Your fix makes sense and I'd be happy to accept a PR. This is from some recent code change and looks like we need some gate to test the non pinterest path.

**Comment by kingsquirrel152** [comment]
Done. https://github.com/pinterest/teletraan/pull/562

**Comment by kingsquirrel152** [comment]
Thanks for the quick turn around!
