### ISSUE TITLE
add ability to run teletraanservice/bin/run.sh in the foreground

### ISSUE THREAD

**Issue by a86c6f7964** [pinterest/teletraan#60]
Currently the script only allows running in the background. If I wrap this in something like systemd or supervisord then sometimes it can be helpful to just have it run in the foreground, or write out a PID file that a daemon watcher can watch.

I would suggest just creating a new command called 'run' similar to the way that catilina.sh does it. Where 'start' will run in the background and 'run' will run the background.

**Comment by sbaogang** [comment]
Thanks for the suggestion, we will merge the changes soon:
https://github.com/pinterest/teletraan/pull/62

That said, we only regard these run.sh for development purpose - for production, it is recommended to create new scripts with all production settings.

Also, you can take a look at how we internally use Teletraan itself to deploy and run Teletraan:
https://github.com/pinterest/teletraan/wiki/Integrate-with-Teletraan

**Comment by a86c6f7964** [comment]
If you do not want the run.sh script to be used in production, then any time that I upgrade I will have to re-read the run.sh script and make any updates that are needed (like change in garbage collectors, memory size's, classpath) to my own local copy of the script. I feel like it would be nice if there was a recommended run script for production. If anything it could just be a bash script that calls 'exec' at the end so that it just sets up the things mentioned above specific to that version of the code.

**Comment by sbaogang** [comment]
Usually you create your own run.sh and server.yaml in different location. I would imagine adopters would like to customize their run.sh and server.yaml to fit their usage. That said, we would make the default run.sh more production-worthy.

**Comment by sbaogang** [comment]
The fix is merged, by default or provide run as argument, run.sh will run in foreground,I am closing this for now, please reopen or create new issues for any further questions. Thanks again for the suggestions!
