### ISSUE TITLE
Current builds on ngapp2 overview pages are incorrect

### ISSUE THREAD

**Issue by chrislloyd** [pinterest/teletraan#605]
When viewing the overview page for an A/B deploy, the currently serving SHA is different than when viewing an environment directly:

<img width="499" alt="screen shot 2018-09-13 at 9 43 23 am" src="https://user-images.githubusercontent.com/718/45502712-89ef9980-b739-11e8-95ad-d0a4326b63a6.png">

In the A cluster:

<img width="352" alt="screen shot 2018-09-13 at 9 43 35 am" src="https://user-images.githubusercontent.com/718/45502718-8e1bb700-b739-11e8-9f1d-0c7539b615be.png">

In the B cluster:

<img width="348" alt="screen shot 2018-09-13 at 9 43 31 am" src="https://user-images.githubusercontent.com/718/45502714-8bb95d00-b739-11e8-858d-eafbcbe50cf9.png">

**Comment by yongwen** [comment]
Hi @chrislloyd Thanks for reporting this. I think the info displayed in the Teletraan UI is based on the value in ZK fields:
        curr_build = ok_to_serve.get('default')
        prev_build = ngapp2_deploy_utils.get_previous_build()
I suspected that the inconsistency here is caused by the unexpected value in the ZK entries.

**Comment by yongwen** [comment]
if we fixed the previous field entry in ZK, I am fairly confident that the display in the page will be correct.

**Comment by TheLat** [comment]
I'll be investigating it, so I'll let you know.

**Comment by chrislloyd** [comment]
It's a bit weird that it needs to read from ZK for this (or at least it's a different entry from the individual env pages).
