### ISSUE TITLE
Add sample deployable app with scripts

### ISSUE THREAD

**Issue by thiagolocatelli** [pinterest/teletraan#61]
Please,

Is it possible to add a sample demo application with sample deployment scripts?

Thanks

**Comment by sbaogang** [comment]
Thanks for the question! deploy-sentinel is the sample application we provided for demo purpose, you can check it out at: https://github.com/pinterest/teletraan/tree/master/deploy-sentinel. Unfortunately, different application has very different config management needs, it is hard to generalize them. deploy-sentinel does provide some ideas on how to write Deploy Scripts. Also more doc could be found on: https://github.com/pinterest/teletraan/wiki/Integrate-with-Teletraan#make-application-deployable. I am closing this for now, but feel free to reopen or open new request on any further questions on how to write deploy scripts. Thanks!

**Comment by thiagolocatelli** [comment]
Hi @sbaogang 

I am very interest in using it but I have a few questions. Can I reach you by email with me questions? Thank you

**Comment by michaelfu** [comment]
@thiagolocatelli You can feel free to reach the Teletraan team by emailing teletraan-users@googlegroups.com.

**Comment by sbaogang** [comment]
Yes, please send your question to teletraan-users@googlegroups.com. We will reply there ( and possibly benefit more people). Thanks!
