### ISSUE TITLE
teletraan & docker

### ISSUE THREAD

**Issue by a93ushakov** [pinterest/teletraan#66]
For using `teletraan` with docker containers `teletraan` must be installed in container?

**Comment by sbaogang** [comment]
Thanks for the question -not supported right now, but coming down the pipeline.

**Comment by a93ushakov** [comment]
Thanks for reply, 

but why not supported? Docker container for `Teletraan`  should be normal host.

**Comment by sbaogang** [comment]
I misunderstood your question - yes, Teletraan should be able to run in container as well - as long as jvm is provided.
