### ISSUE TITLE
Request: Containerization/Kubernetes?

### ISSUE THREAD

**Issue by aronchick** [pinterest/teletraan#68]
Has anyone looked at supporting containers/Kubernetes as a deployment object, or containerizing Teletraan for running on Kubernetes? We'd love to help :)

Full disclosure: I work at Google on Kubernetes/GKE.

**Comment by sbaogang** [comment]
Thanks for reaching out! We are actively discussing how teletraan is going to support containers, especially what orchestrators or cluster managers to support. Ideally teletraan could support most of the major technologies - would love to get touch and have further discussions!  The team is not very familiar with Kubernetes and how could the two products integrate. What kind of help you guys could provide?

**Comment by aronchick** [comment]
Well, it's up to you! We could give your team an overview of Kubernetes &
Containers, talk about how to target the platform as a deployment, help you
move your code to containers, you name it. What do you have first on your
roadmap?

**Comment by sbaogang** [comment]
We have been working on mesos framework prototyping recently. We'd like to understand more about Kubernetes in the meantime. If we could invite one of your engineers to give a tech talk here at Pinterest, and we can go from there!

**Comment by aronchick** [comment]
Hi!

Can you ping me - aronchick@google? Let's take this out of GH :)

**Comment by sbaogang** [comment]
Thanks for reaching out. communicate through private channel, will provide update through roadmap once we have something more concrete. Closing for now.
