### ISSUE TITLE
Quick start documentation glitches

### ISSUE THREAD

**Issue by vdboor** [pinterest/teletraan#77]
I've tried getting the demo working, and it wasn't quite a smooth ride. I hope this feedback helps you guys smoothen that.
- after vagrant up: no service is running at http://127.0.0.1:8888/
- Trying the demo failed on `sed` calls in Linux:

```
vagrant@vagrant-ubuntu-trusty-64:~$ curl -O https://raw.githubusercontent.com/pinterest/teletraan/master/deploy-sentinel/demo_run.sh
...
...
Teletraan server downloaded
+ sed -i '' 's/type: mysql/#type: mysql/' ./deploy-service/bin/server.yaml
sed: can't read s/type: mysql/#type: mysql/: No such file or directory
```

the fix is using `sed -i''` instead of `sed -i ''`. I hope that doesn't conflict with OSX's sed.
- "Create a new Environment" (https://github.com/pinterest/teletraan/wiki/Quickstart-Guide#run-demo ) 
  I was a bit confused about pushing the Capacity button. It took me some time to realize the "Create" button had to be used first. Funny I know :)
- Creating the deploy gives `KeyError: 'provisioningHosts'`

I like your error message though :joy:

**Comment by nickdechant** [comment]
Hey there!
Thanks for the feedback and details! :+1: 
Looks like it works for us running Vagrant 1.8.1 so it's curious that the service isn't running on :8888. Perhaps trying it on Vagrant 1.8.1 will work for you. Is that the version you are using? 

The sed issue is definitely a difference in how Linux vs OS X handles the command. Thanks for pointing this out. I will fix this in a future release.

Sorry about the 'KeyError: provisioningHosts' error. It would be great if you could provide the whole stack trace it presents to you on the error page so we can look more into it. :smile:
