### ISSUE TITLE
Wrong url in board's host link when ec2-ip-... is used

### ISSUE THREAD

**Issue by devenv** [pinterest/teletraan#94]
e.g.
http://teletraan/env/Bidder/Production/host/x.x.x.x
instead of
http://teletraan/env/Bidder/Production/host/ip-x-x-x-x

It doesn't load too as the host becomes just the first x, i.e.:
Home / Environments / Env1 (Production) / host / x

**Comment by sbaogang** [comment]
Can you do a "select * from hosts;" in your mysql console and tell us what the hostname looks like?

We recommend to follow this page to provide host_info file with the legit hostname in it:
https://github.com/pinterest/teletraan/wiki/Integrate-with-Teletraan#provide-host-info-file-optional?

**Comment by devenv** [comment]
+-------------------------------+------------------+----------------+---------------+---------------+---------------+--------+
| host_id                       | host_name        | group_name     | ip            | create_date   | last_update   | state  |
+-------------------------------+------------------+----------------+---------------+---------------+---------------+--------+
| ip-x-x-x-111               | ip-x-x-x-111  | group1      | x.x.x.111  | 1459178819951 | 1459264214300 | ACTIVE |
| ip-x-x-x-29                | ip-x-x-x-29   | group2    | x.x.x.29   | 1459249090032 | 1459264189644 | ACTIVE |

And so on, no duplicates if it's relevant...

**Comment by yujunglo** [comment]
Hi,
Our UI can read the data you gave correctly. Could you please paste the screenshot of the env to help us reproduce it? (url: http://teletraan/env/Bidder/Production/) Thanks.

**Comment by devenv** [comment]
![teletraan](https://cloud.githubusercontent.com/assets/304936/14284004/4c3989e2-fb4e-11e5-9f2e-15be68f59fa7.png)

**Comment by devenv** [comment]
![teletraan](https://cloud.githubusercontent.com/assets/304936/14284210/32c0e9c8-fb4f-11e5-8502-49cf88f86786.png)

**Comment by devenv** [comment]
![teletraan](https://cloud.githubusercontent.com/assets/304936/14284221/41196f2c-fb4f-11e5-8e73-6d26d4ce5fe5.png)

**Comment by yujunglo** [comment]
Thanks for the detailed screenshot. We suspect you might use the bad commit. Would you mind to rebase to the latest? Thanks.
